### ISSUE TITLE
Add option to charge per use of the /tpa command

### ISSUE THREAD

**Issue by TechRoot** [WiIIiam278/HuskHomes2#167]
As a suggestion:

Add TPA into Economy builtin system, so we can setup a fee for TPA usage.
Also, permission nodes to avoid this cost would be implemented.

**Comment by WiIIiam278** [comment]
This is already a feature:
```
economy_integration:
  enabled: false
  free_home_slots: 5
  costs:
    additional_home_slot: 100
    make_home_public: 50
    random_teleport: 20
    back: 0
    ```
