### ISSUE TITLE
Imported public homes & warps won't appear on map hooks due to UUID zeroing on import

### ISSUE THREAD

**Issue by ApliNi** [WiIIiam278/HuskHomes2#215]
I have map integration enabled, but there are no teleports in the map.  
This is the config for map integration: 
```
map_hook:
  enabled: true
  map_plugin: DYNMAP
  show_public_homes: false
  show_warps: true
```

Edit: 
Dynmap: `3.4-beta-5`.  
HuskHomes: `v3.0.2`.  
(HuskHomes 2.x does not have this problem)  

This is the json in the dynmap database: (This map has over 47 warps.)
![image](https://user-images.githubusercontent.com/59365724/189688346-00ed068f-5711-4791-867d-ef81c78d18ed.png)

Do I need to provide other information?
