### ISSUE TITLE
Map hook locales aren't translatable

### ISSUE THREAD

**Issue by ApliNi** [WiIIiam278/HuskHomes2#218]
![image](https://user-images.githubusercontent.com/59365724/190454094-872c572b-2f75-4a24-8e4b-28929851fe55.png)

I would like to be able to edit the messages and spaces displayed on the dynmap in message.yml so I can delete them and have the dynmap only show the warp instructions. Or translate them. 

Edit: I noticed that json in dynmap is html text, is it possible to edit it directly in message.yml?

**Comment by WiIIiam278** [comment]
These are currently untranslatable

https://github.com/WiIIiam278/HuskHomes2/blob/f80261d919d34236fa47513d0e02b1f0af4bf923/bukkit/src/main/java/net/william278/huskhomes/hook/DynMapHook.java#L76-L78

https://github.com/WiIIiam278/HuskHomes2/blob/f80261d919d34236fa47513d0e02b1f0af4bf923/bukkit/src/main/java/net/william278/huskhomes/hook/DynMapHook.java#L112-L113

With that said... I don't think Dynmap (the web panel itself) offers international locales, does it? The plan hook is also not translatable as doing so is a bit messy since labels are added via annotations

**Comment by ApliNi** [comment]
Maybe it doesn't matter to me anymore, I found other ways to hide it. You can add this feature if you want (I'll translate it)
```css
/*地标名称*/
.dynmap .mapMarker .markerName{
	top: -10px !important;
	border-radius: 0 !important;
    padding: 1px 5px !important;
	
	/*始终显示*/
	display: block;
    position: absolute;
    z-index: 16;
    white-space: nowrap;
    background: rgba(0,0,0,0.6);
}
/*一个错位和溢出*/
.dynmap .leaflet-interactive{
	width: 0px;
    height: 0px;
}
/*白色悬浮框位置*/
.leaflet-fade-anim .leaflet-map-pane .leaflet-popup{
	bottom: -35px !important;
    left: 10px !important;
}
	/*白色悬浮框圆角*/
	.leaflet-popup-content-wrapper{
		border-radius: 0;
	}
	/*白色悬浮框大小*/
	.leaflet-popup-content {
		margin: 5px 12px;
	}
		/*点击后选中*/
		.MarkerPopup:first-child{
		    user-select: all;
		}
		/*隐藏多余标签*/
		.MarkerPopup div *{
			display: none;
		}
```
