### ISSUE TITLE
Why is the plugin still overwriting my original EssentialsX's original directives even though I've disabled the directive?

### ISSUE THREAD

**Issue by twseer67875** [WiIIiam278/HuskHomes2#347]
Why is the plugin still overwriting my original EssentialsX's original directives even though I've disabled the directive?
How do I completely turn off specific features I want?

`disabled_commands: ['/home']`

https://user-images.githubusercontent.com/70073452/230730948-bb29ec55-ecba-438a-b8c2-1def03558c6d.mp4

Plugin Version: `4.1.1`
Server Version: `This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)`

config.yml
```
# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃       HuskHomes Config       ┃
# ┃    Developed by William278   ┃
# ┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
# ┣╸ Information: https://william278.net/project/huskhomes
# ┗╸ Documentation: https://william278.net/docs/huskhomes
language: en-gb
check_for_updates: true
debug_logging: false
database:
  # Database connection settings
  type: SQLITE
  mysql:
    credentials:
      host: localhost
      port: 3306
      database: HuskHomes
      username: root
      password: pa55w0rd
      parameters: ?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    connection_pool:
      # MySQL connection pool properties
      size: 12
      idle: 12
      lifetime: 1800000
      keepalive: 30000
      timeout: 20000
  table_names:
    saved_position_data: huskhomes_saved_positions
    position_data: huskhomes_position_data
    home_data: huskhomes_homes
    warp_data: huskhomes_warps
    teleport_data: huskhomes_teleports
    player_data: huskhomes_users
general:
  # General plugin settings
  max_homes: 10
  max_public_homes: 10
  stack_permission_limits: true
  permission_restrict_warps: false
  overwrite_existing_homes_warps: true
  teleport_warmup_time: 5
  teleport_warmup_display: ACTION_BAR
  teleport_request_expiry_time: 60
  strict_tpa_here_requests: true
  allow_unicode_names: false
  allow_unicode_descriptions: true
  back_command_return_by_death: true
  back_command_save_teleport_event: false
  list_items_per_page: 12
  asynchronous_teleports: true
  play_sound_effects: true
  sound_effects:
    teleportation_warmup: block.note_block.banjo
    teleportation_complete: entity.enderman.teleport
    teleportation_cancelled: entity.item.break
cross_server:
  # Enable teleporting across proxied servers. Requires MySQL
  enabled: false
  messenger_type: PLUGIN_MESSAGE
  cluster_id: ''
  global_spawn:
    enabled: false
    warp_name: Spawn
  global_respawning: false
  redis_credentials:
    host: localhost
    port: 6379
    password: ''
    use_ssl: false
rtp:
  # Random teleport (/rtp) command settings
  cooldown_length: 10
  radius: 5000
  spawn_radius: 500
  distribution_mean: 0.75
  distribution_deviation: 2.0
  restricted_worlds:
  - world_nether
  - world_the_end
economy:
  # Charge for certain actions (requires Vault)
  enabled: false
  # Use this currency for payments (works only with RedisEconomy), defaults to Vault currency
  redis_economy_name: vault
  free_home_slots: 5
  costs:
    back_command: 0.0
    additional_home_slot: 100.0
    random_teleport: 25.0
    make_home_public: 50.0
map_hook:
  # Display public homes/warps on web maps (DYNMAP, BLUEMAP)
  enabled: false
  map_plugin: DYNMAP
  show_public_homes: true
  show_warps: true
# Disabled commands (e.g. ['/home', '/warp'] to disable /home and /warp)
disabled_commands: ['/home']
```

**Comment by WiIIiam278** [comment]
HuskHomes on Minecraft 1.19.3< runs as a Spigot plugin. Spigot does not provide API for programatically registering commands, so the command will still register but just display a "disabled message". 

Please create command alises in command.yml to point `/home` --> `/essentials:home` ([link](https://bukkit.fandom.com/wiki/Commands.yml))

OR

Update your Minecraft Server to Paper 1.19.4. HuskHomes on Paper 1.19.4 will run as a Paper plugin, which does allow for this. Thus, disabled commands won't be registered and Essentials commands will work by default.

**Comment by twseer67875** [comment]
> HuskHomes on Minecraft 1.19.3< runs as a **Spigot plugin**. Spigot does not provide API for programatically registering commands, so the command will still register but just display a "disabled" message.
> 
> Please create command alises in command.yml to point `/home` -> `/essentials:home` ([link](https://bukkit.fandom.com/wiki/Commands.yml)) -- and do this for every command.
> 
> OR
> 
> Update your Minecraft Server to Paper 1.19.4. HuskHomes on Paper 1.19.4 will run as a **Paper plugin**, which does allow for this. Thus, disabled commands won't be registered and Essentials commands will work by default.

I used the second way, tried to upgrade the version to 1.19.4, but instead of solving the problem, it got worse...
Now with the same configuration, the command cannot be disabled, I try to specify the EssentialsX home command directly inside the directive is also overridden as huskhomes...

https://user-images.githubusercontent.com/70073452/230733589-8b6841ef-5af9-4f3b-b844-1e5910b1ccd5.mp4


Plugin Version: `4.1.1`
Server Version: `This server is running Paper version git-Paper-499 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 29b17a8)`

**Comment by WiIIiam278** [comment]
Send your commands.yml

**Comment by twseer67875** [comment]
> Send your commands.yml and HuskHomes config.yml, it looks like you've set some weird aliases

config.yml
```
# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃       HuskHomes Config       ┃
# ┃    Developed by William278   ┃
# ┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
# ┣╸ Information: https://william278.net/project/huskhomes
# ┗╸ Documentation: https://william278.net/docs/huskhomes
language: en-gb
check_for_updates: true
debug_logging: false
database:
  # Database connection settings
  type: SQLITE
  mysql:
    credentials:
      host: localhost
      port: 3306
      database: HuskHomes
      username: root
      password: pa55w0rd
      parameters: ?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    connection_pool:
      # MySQL connection pool properties
      size: 12
      idle: 12
      lifetime: 1800000
      keepalive: 30000
      timeout: 20000
  table_names:
    saved_position_data: huskhomes_saved_positions
    position_data: huskhomes_position_data
    home_data: huskhomes_homes
    warp_data: huskhomes_warps
    teleport_data: huskhomes_teleports
    player_data: huskhomes_users
general:
  # General plugin settings
  max_homes: 10
  max_public_homes: 10
  stack_permission_limits: true
  permission_restrict_warps: false
  overwrite_existing_homes_warps: true
  teleport_warmup_time: 5
  teleport_warmup_display: ACTION_BAR
  teleport_request_expiry_time: 60
  strict_tpa_here_requests: true
  allow_unicode_names: false
  allow_unicode_descriptions: true
  back_command_return_by_death: true
  back_command_save_teleport_event: false
  list_items_per_page: 12
  asynchronous_teleports: true
  play_sound_effects: true
  sound_effects:
    teleportation_warmup: block.note_block.banjo
    teleportation_complete: entity.enderman.teleport
    teleportation_cancelled: entity.item.break
cross_server:
  # Enable teleporting across proxied servers. Requires MySQL
  enabled: false
  messenger_type: PLUGIN_MESSAGE
  cluster_id: ''
  global_spawn:
    enabled: false
    warp_name: Spawn
  global_respawning: false
  redis_credentials:
    host: localhost
    port: 6379
    password: ''
    use_ssl: false
rtp:
  # Random teleport (/rtp) command settings
  cooldown_length: 10
  radius: 5000
  spawn_radius: 500
  distribution_mean: 0.75
  distribution_deviation: 2.0
  restricted_worlds:
  - world_nether
  - world_the_end
economy:
  # Charge for certain actions (requires Vault)
  enabled: false
  # Use this currency for payments (works only with RedisEconomy), defaults to Vault currency
  redis_economy_name: vault
  free_home_slots: 5
  costs:
    back_command: 0.0
    additional_home_slot: 100.0
    random_teleport: 25.0
    make_home_public: 50.0
map_hook:
  # Display public homes/warps on web maps (DYNMAP, BLUEMAP)
  enabled: false
  map_plugin: DYNMAP
  show_public_homes: true
  show_warps: true
# Disabled commands (e.g. ['/home', '/warp'] to disable /home and /warp)
disabled_commands: ['/home', '/warp']
```

commands.yml
```
command-block-overrides: []
ignore-vanilla-permissions: false
aliases:
  icanhasbukkit:
  - version $1-
```
