### ISSUE TITLE
Dynmap hook is not populating with existing homes & warps on startup

### ISSUE THREAD

**Issue by ApliNi** [WiIIiam278/HuskHomes2#416]
The current version is 4.3.2, I updated from 3.x and found that no teleportation points are displayed on the dynmap. 

```yaml
map_hook:
  # Display public homes/warps on your web map (supports Dynmap and BlueMap)
  enabled: true
  show_public_homes: true
  show_warps: true
```
