### ISSUE TITLE
Button locale not handling color codes (`&`)

### ISSUE THREAD

**Issue by Log1x** [WiIIiam278/HuskHomes2#43]
Example of items that do not parse colors:

```yaml
edit_warp_teleport_button: '[Teleport]'
edit_warp_teleport_button_tooltip: Teleport to this warp
edit_warp_delete_button: '[Delete]'
edit_warp_delete_button_tooltip: Delete this warp
edit_warp_relocate_button: '[Relocate]'
edit_warp_relocate_button_tooltip: Update this warp's location
edit_warp_rename_button: '[Rename]'
edit_warp_rename_button_tooltip: Change the name of this warp
edit_warp_description_button: '[Edit Description]'
edit_warp_description_button_tooltip: Update this warp's description
edit_home_teleport_button: '[Teleport]'
edit_home_teleport_button_tooltip: Teleport to your home
edit_home_delete_button: '[Delete]'
edit_home_delete_button_tooltip: Delete your home
edit_home_relocate_button: '[Relocate]'
edit_home_relocate_button_tooltip: Update your home's location
edit_home_rename_button: '[Rename]'
edit_home_rename_button_tooltip: Change the &aname&7 of your home
edit_home_description_button: '[Edit Description]'
edit_home_description_button_tooltip: Update the &adescription&7 of your home
edit_home_make_public_button: '[Make Public]'
edit_home_make_public_button_tooltip: Open your home to the public
edit_home_make_private_button: '[Make Private]'
edit_home_make_private_button_tooltip: Make your home private
home_default_description: '&a%1%''s&7 home'
warp_default_description: A &apublicly&7 accessible warp
```
